# Generated by Django 5.2.6 on 2025-09-28 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('descriptive', 'Descriptive Statistics'), ('diagnostic', 'Diagnostic Analysis'), ('predictive', 'Predictive Analysis'), ('prescriptive', 'Prescriptive Analysis'), ('cohort', 'Cohort Analysis'), ('trend', 'Trend Analysis'), ('correlation', 'Correlation Analysis'), ('outlier', 'Outlier Detection')], max_length=20)),
                ('query_executed', models.TextField()),
                ('raw_data', models.JSONField(default=dict)),
                ('statistical_insights', models.JSONField(default=dict)),
                ('visualizations', models.JSONField(default=list)),
                ('recommendations', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_reports', to='chat.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('customer', 'Customer Metrics'), ('financial', 'Financial Metrics'), ('operational', 'Operational Metrics'), ('risk', 'Risk Metrics'), ('growth', 'Growth Metrics')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='count', max_length=50)),
                ('calculation_method', models.TextField()),
                ('sql_query', models.TextField()),
                ('benchmark_value', models.FloatField(blank=True, null=True)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('is_kpi', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-calculated_at'],
                'unique_together': {('name', 'calculated_at')},
            },
        ),
        migrations.CreateModel(
            name='DataInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('trend', 'Trend'), ('anomaly', 'Anomaly'), ('correlation', 'Correlation'), ('pattern', 'Pattern'), ('threshold', 'Threshold Alert'), ('forecast', 'Forecast')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('significance_level', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='analytics.analysisreport')),
            ],
            options={
                'ordering': ['-significance_level', '-created_at'],
            },
        ),
    ]
